### ISSUE TITLE
400 response from Paypal on rake task `workarea:paypal:create_webhooks`

### ISSUE THREAD

**Issue by alejandrobabio** [workarea-commerce/workarea-paypal#11]
**Describe the bug**
The rake task `workarea:Paypal:create_webhooks` does not create new webhooks. 
The response that I got from Paypal was that the `url` parameter was empty (this is not true but was a lead).

**To Reproduce**
This is the output that I got:
```
root@app-dc46995d8-k4t9d:/workarea# SITE_ID=spell_aus WORKAREA_PAYPAL_CLIENT_ID=********** WORKAREA_PAYPAL_CLIENT_SECRET=********* bundle exec rake workarea:paypal:create_webhooks
W, [2020-04-15T17:40:11.407604 #2673]  WARN -- sentry: ** [Raven] Unable to load raven/integrations/rack-timeout: uninitialized constant Rack::Timeout::RequestTimeoutException
DEPRECATION WARNING: define_block_types is deprecated and will be removed from Workarea 3.6 (Use `Workarea.define_content_block_types` instead.) (called from <top (required)> at /workarea/config/environment.rb:5)
DEPRECATION WARNING: define_block_types is deprecated and will be removed from Workarea 3.6 (Use `Workarea.define_content_block_types` instead.) (called from <top (required)> at /workarea/config/environment.rb:5)
DEPRECATION WARNING: define_block_types is deprecated and will be removed from Workarea 3.6 (Use `Workarea.define_content_block_types` instead.) (called from <top (required)> at /workarea/config/environment.rb:5)
/workarea/config/initializers/rack_attack.rb:3: warning: already initialized constant Rack::Attack::KUBERNETES_IP_ADDRESS
/workarea/vendored_gems/ruby/2.6.0/gems/workarea-core-3.5.5/config/initializers/13_rack_attack.rb:20: warning: previous definition of KUBERNETES_IP_ADDRESS was here
Unsubscribing existing webhooks...
Subscribing to PayPal webhook events...
rake aborted!
Workarea::Paypal::Gateway::RequestError: 400 : PayPal request error, debug ID ["c0bdef42352b9"]
/workarea/vendored_gems/ruby/2.6.0/gems/workarea-paypal-3.0.1/lib/workarea/paypal/gateway.rb:165:in `throw_request_error'
/workarea/vendored_gems/ruby/2.6.0/gems/workarea-paypal-3.0.1/lib/workarea/paypal/gateway.rb:180:in `rescue in handle_connection_errors'
/workarea/vendored_gems/ruby/2.6.0/gems/workarea-paypal-3.0.1/lib/workarea/paypal/gateway.rb:174:in `handle_connection_errors'
/workarea/vendored_gems/ruby/2.6.0/gems/workarea-paypal-3.0.1/lib/workarea/paypal/gateway.rb:124:in `create_webhook'
/workarea/vendored_gems/ruby/2.6.0/gems/workarea-paypal-3.0.1/lib/tasks/workarea/create_webhooks.rake:18:in `block (3 levels) in <top (required)>'
/workarea/vendored_gems/ruby/2.6.0/gems/elastic-apm-2.12.0/lib/elastic_apm/spies/rake.rb:17:in `execute'
/workarea/vendored_gems/ruby/2.6.0/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'
/usr/local/rbenv/versions/2.6.5/bin/bundle:23:in `load'
/usr/local/rbenv/versions/2.6.5/bin/bundle:23:in `<main>'

Caused by:
PayPalHttp::HttpError: PayPalHttp::HttpError
/workarea/vendored_gems/ruby/2.6.0/gems/paypalhttp-1.0.0/lib/paypalhttp/http_client.rb:110:in `_parse_response'
/workarea/vendored_gems/ruby/2.6.0/gems/paypalhttp-1.0.0/lib/paypalhttp/http_client.rb:81:in `block in execute'
/workarea/vendored_gems/ruby/2.6.0/gems/paypalhttp-1.0.0/lib/paypalhttp/http_client.rb:80:in `execute'
/workarea/vendored_gems/ruby/2.6.0/gems/workarea-paypal-3.0.1/lib/workarea/paypal/gateway.rb:22:in `send_request'
/workarea/vendored_gems/ruby/2.6.0/gems/workarea-paypal-3.0.1/lib/workarea/paypal/gateway.rb:124:in `block in create_webhook'
/workarea/vendored_gems/ruby/2.6.0/gems/workarea-paypal-3.0.1/lib/workarea/paypal/gateway.rb:176:in `handle_connection_errors'
/workarea/vendored_gems/ruby/2.6.0/gems/workarea-paypal-3.0.1/lib/workarea/paypal/gateway.rb:124:in `create_webhook'
/workarea/vendored_gems/ruby/2.6.0/gems/workarea-paypal-3.0.1/lib/tasks/workarea/create_webhooks.rake:18:in `block (3 levels) in <top (required)>'
/workarea/vendored_gems/ruby/2.6.0/gems/elastic-apm-2.12.0/lib/elastic_apm/spies/rake.rb:17:in `execute'
/workarea/vendored_gems/ruby/2.6.0/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'
/usr/local/rbenv/versions/2.6.5/bin/bundle:23:in `load'
/usr/local/rbenv/versions/2.6.5/bin/bundle:23:in `<main>'
Tasks: TOP => workarea:paypal:create_webhooks
(See full trace by running task with --trace)
root@app-dc46995d8-k4t9d:/workarea# 
```

**Expected behavior**
The webhooks were added to my sandbox account (in this case).

**Workarea Setup (please complete the following information):**
workarea 3.5.5
workarea-multi_site 3.2.1
workarea-paypal 3.0.1

**Additional context**
I figured out what was happening running in the console the same code that the rake task was using:
```
irb(main):006:0> result = Workarea::Paypal.gateway.create_webhook(url: Workarea::Storefront::Engine.routes.url_helpers.paypal_event_url(host: Workarea.config.host), event_types: Workarea.config.default_webhook_events)
Traceback (most recent call last):
        1: from (irb):6
Workarea::Paypal::Gateway::RequestError (400 : PayPal request error, debug ID ["7088b5c2e11a0"])
```
But with a little tweak, adding the https protocol, I made it work.
```
irb(main):014:0> result = Workarea::Paypal.gateway.create_webhook(url: Workarea::Storefront::Engine.routes.url_helpers.paypal_event_url(host: Workarea.config.host, protocol: 'https'), event_types: Workarea.config.default_webhook_events)
=> #<OpenStruct status_code=201, result=#<OpenStruct id= ... >
```
**Sumarizing**
Updating the rake task changing the `url` parameter in `create_webhook` to
```
Workarea::Storefront::Engine.routes.url_helpers.paypal_event_url(host: Workarea.config.host, protocol: 'https')
```
Will fix the issue.

**Comment by bencrouse** [comment]
Thanks for investigating and reporting @alejandrobabio, I've opened a PR here if you have a minute to take a look: https://github.com/workarea-commerce/workarea-paypal/pull/13

We'll get this released shortly.

**Comment by alejandrobabio** [comment]
Looks good. Thank you.
